language: java
jdk:
 - oraclejdk8
services:
  - mysql 
before_script:
  - sh -c "mysql -e 'CREATE DATABASE test;'"
  - sh -c "mysql -e 'CREATE TABLE test.info ( id bigint NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;'"
  - sh -c "mysql -e 'INSERT INTO test.info (name) VALUES ((sha2(rand(), 256)));'"

script:
   - mvn install